package application;

import java.util.Random;

//import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.image.Image;

public class GUIController {

    @FXML
    private Button scissors_button;

    @FXML
    private ImageView scissors_image;

    @FXML
    private Button spock_button;

    @FXML
    private ImageView spock_image;

    @FXML
    private Button lizard_button;

    @FXML
    private ImageView lizard_image;

    @FXML
    private Button rock_button;

    @FXML
    private ImageView rock_image;

    @FXML
    private Button paper_button;

    @FXML
    private ImageView paper_image;

    @FXML
    private Button clear_button;

    @FXML
    private ImageView user_display;

    @FXML
    private ImageView computer_display;

    @FXML
    private Label winner_statement;

    @FXML
    void playersChoiceLizard(MouseEvent event) {
    	user_display.setImage(lizardI);
    	autogeneratedChoice();
    }

	@FXML
    void playersChoicePaper(MouseEvent event) {
		user_display.setImage(paperI);
    	autogeneratedChoice();
    }

    @FXML
    void playersChoiceRock(MouseEvent event) {
    	user_display.setImage(rockI);
    	autogeneratedChoice();
    }

    @FXML
    void playersChoiceScissors(MouseEvent event) {
    	user_display.setImage(scissorsI);
    	autogeneratedChoice();
    }

    @FXML
    void playersChoiceSpock(MouseEvent event) {
    	user_display.setImage(spockI);
    	autogeneratedChoice();
    }



    private Image rockI;
    private Image paperI;	
    private Image scissorsI;	
    private Image lizardI;	
    private Image spockI;	
    
    public void initialize(){
    	
    	rockI = new Image("rock.jpg");
    	paperI = new Image("paper.jpg");
    	scissorsI = new Image("scissors.jpg");
    	lizardI = new Image("lizard.jpg");
    	spockI = new Image("spock.jpg");

    }
  


   		public int autogeneratedChoice(){
    	
    	Random randomNum = new Random();
        int randomNumber = randomNum.nextInt(4);
        
        String choice = null;
        
        switch(randomNumber){
        case 0: choice = "Rock";
        	computer_display.setImage(rockI);
            break;
        case 1: choice = "Paper";
        	computer_display.setImage(paperI);
            break;
        case 2: choice = "Scissors";
        	computer_display.setImage(scissorsI);
            break;
        case 3: choice = "Lizard";
        	computer_display.setImage(lizardI);
        	break;
        case 4: choice = "Spock";
        	computer_display.setImage(spockI);
        }
        return randomNumber;
        }
}




